In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os, random, shutil, time

import warnings
warnings.filterwarnings('ignore')

import sys

In [2]:
starting_dir = os.getcwd()
print (starting_dir)

/Users/kimd999/research/script_not_in_dropbox/srpAnalytics/analysis/latest/0_before_reformat

In [4]:
#before reformat, and bmd
file_path = '/Users/kimd999/research/projects/toxicity/per_each_data/phase_I_II/input/morpho/tall/2_after_fixing_MO24/final_full/zf_morphology_data_335_chemicals_2020DEC16_fixed.csv'
df = pd.read_csv(file_path, header = 0)
display(df.head())

display (len(np.unique(df['chemical.id'])))

   chemical.id bottle.id  conc plate.id well      date endpoint  value
0         1030    C48962   0.0     9414  A06  20151028     MO24    0.0
1         1030    C48962   0.0     9414  B06  20151028     MO24    0.0
2         1030    C48962   0.0     9414  C06  20151028     MO24    0.0
3         1030    C48962   0.0     9414  D06  20151028     MO24    0.0
4         1030    C48962   0.0     9414  E06  20151028     MO24    0.0

335

In [5]:
#after reformat and bmd calculation
file_path = '/Users/kimd999/research/projects/toxicity/per_each_data/phase_I_II/output/morphology/2021_04_27_after_Lisa_fix/output/bmd_vals_2021_04_26.csv'
df_after_reformat_bmd = pd.read_csv(file_path, header = 0)
display(df_after_reformat_bmd.head())

display (len(np.unique(df['chemical.id'])))

,Chemical_ID,End_Point,Model,BMD10,BMDL,BMD50,AUC,Min_Dose,Max_Dose,AUC_Norm,DataQC_Flag,BMD_Analysis_Flag,BMD10_Flag,BMD50_Flag
0,53,ANY24,NaN,NaN,NaN,NaN,3.840625,0.0,50.0,0.076812,1,NaN,NaN,NaN
1,53,ANY120,NaN,NaN,NaN,NaN,4.943750,0.0,50.0,0.098875,1,NaN,NaN,NaN
2,53,AXIS,weibull,4507.931977,NaN,1.891008e+12,2.781351,0.0,50.0,0.055627,4,0.0,1.0,1.0
3,53,ALL_BUT_MORT,weibull,inf,NaN,inf,4.070161,0.0,50.0,0.081403,4,0.0,1.0,1.0
4,53,BRN_,weibull,4507.931977,NaN,1.891008e+12,2.781351,0.0,50.0,0.055627,4,0.0,1.0,1.0

335