In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os, random, shutil, time
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

import sys

from datetime import datetime

In [2]:
starting_dir = os.getcwd()
print (starting_dir)

/Users/kimd999/research/script_not_in_dropbox/srpAnalytics/code/latest/2_bmd/1_before_bmd/phase_I_II/morpho

In [ ]:
complete_input_file_path= '/Users/kimd999/research/projects/toxicity/per_each_data/phase_I_II/input/morpho/wide/2_after_fixing_MO24/zf_morphology_data_335_chemicals_2020DEC16_fixed_wide_DNC_0_full.csv'
df = pd.read_csv(complete_input_file_path, header = 0)
#print(df.columns)

display(df.head())

display (len(np.unique(df['chemical.id'])))
display (np.unique(df['chemical.id']))

display (len(np.unique(df['plate.id'])))
display (np.unique(df['plate.id']))

In [3]:
complete_input_file_path= '/Users/kimd999/research/projects/toxicity/per_each_data/phase_I_II/input/morpho/wide/2_after_fixing_MO24/zf_morphology_data_335_chemicals_2020DEC16_fixed_wide_DNC_0_full.csv'
df = pd.read_csv(complete_input_file_path, header = 0)
#print(df.columns)

display(df.head())

display (len(np.unique(df['chemical.id'])))
display (np.unique(df['chemical.id']))

display (len(np.unique(df['plate.id'])))
display (np.unique(df['plate.id']))

,chemical.id,plate.id,well,chemical_plate_well,conc,AXIS,BRAI,CFIN,CIRC,DNC_,...,PE__,PFIN,PIG_,SM24,SNOU,SOMI,SWIM,TRUN,TR__,YSE_
0,53,9289,A01,53_9289_A01,50.0,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,53,9289,A02,53_9289_A02,35.6,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,53,9289,A03,53_9289_A03,11.2,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,53,9289,A04,53_9289_A04,5.0,1.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,53,9289,A05,53_9289_A05,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

335

array([  53,   54,   56,   57,   58,   60,   61,   62,   63,   64,   65,
         66,   67,   69,   70,  129,  155,  163,  165,  172,  176,  197,
        220,  227,  246,  247,  248,  250,  251,  252,  281,  283,  285,
        286,  295,  296,  297,  332,  337,  338,  339,  342,  355,  357,
        360,  362,  363,  365,  370,  373,  380,  381,  384,  392,  395,
        396,  401,  403,  404,  406,  409,  412,  413,  414,  415,  416,
        417,  418,  419,  420,  421,  441,  447,  448,  470,  471,  472,
        481,  500,  501,  502,  503,  504,  511,  512,  513,  514,  515,
        517,  557,  560,  581,  585,  596,  597,  599,  601,  602,  606,
        607,  609,  618,  628,  629,  667,  674,  689,  691,  694,  696,
        697,  702,  721,  722,  740,  741,  746,  747,  768,  769,  770,
        771,  774,  775,  776,  777,  778,  946,  947,  948,  949,  951,
        952,  961,  965,  966,  998, 1030, 1031, 1105, 1114, 1119, 1161,
       1163, 1166, 1167, 1171, 1172, 1174, 1175, 1176, 1177, 1178, 1179,
       1180, 1182, 1183, 1187, 1211, 1221, 1268, 1271, 1273, 1307, 1310,
       1316, 1327, 1354, 1363, 1370, 1371, 1383, 1391, 1449, 1450, 1454,
       1455, 1532, 1535, 1540, 1595, 1600, 1603, 1606, 1608, 1610, 1611,
       1612, 1613, 1614, 1615, 1617, 1618, 1620, 1627, 1629, 1631, 1651,
       1664, 1666, 1670, 1677, 1689, 1694, 1704, 1706, 1762, 1764, 1770,
       1771, 1790, 1796, 1807, 1808, 1809, 1816, 1827, 1845, 1846, 1853,
       1854, 1855, 1861, 1890, 1906, 1912, 1929, 1930, 1944, 1961, 1965,
       1967, 1968, 1982, 2058, 2067, 2098, 2103, 2104, 2105, 2137, 2141,
       2142, 2154, 2156, 2159, 2165, 2185, 2186, 2187, 2191, 2323, 2324,
       2325, 2326, 2327, 2328, 2371, 2373, 2374, 2406, 2411, 2413, 2414,
       2415, 2417, 2432, 2467, 2496, 2506, 2532, 2573, 2596, 2601, 2635,
       2637, 2638, 2655, 2657, 2661, 2686, 2688, 2691, 2706, 2723, 2726,
       2739, 2740, 2743, 2751, 2752, 2770, 2772, 2774, 2778, 2813, 2827,
       2849, 2877, 2886, 2893, 2896, 2960, 2973, 2989, 3002, 3004, 3005,
       3009, 3012, 3015, 3022, 3055, 3091, 3102, 3104, 3114, 3127, 3138,
       3139, 3140, 3143, 3147, 3151, 3160, 3168, 3169, 3272, 3273, 3411,
       3412, 3413, 3689, 3690, 3757])

725

array(['10061', '10067', '10075', '10080', '10081', '10083', '10090',
       '10091', '10130', '10142', '10184', '10186', '10188', '10190',
       '10191', '10192', '10193', '10250', '10251', '10253', '10255',
       '10465', '10467', '10520', '10531', '10534', '10535', '10591',
       '10593', '10778', '10779', '10938', '10940', '10945', '10970',
       '10998', '10999', '11034', '11035', '11042', '11044', '11069',
       '11070', '11076', '11102', '11108', '11176', '11479', '11542',
       '11620', '11622', '11735', '11928', '11987', '11991', '11998',
       '11999', '12003', '12008', '12085', '12099', '12106', '12317',
       '12362', '12388', '12412', '12439', '12441', '12442', '12446',
       '12447', '12494', '12496', '12512', '12515', '12517', '12546',
       '12552', '12563', '12564', '12567', '12570', '12571', '12594',
       '12789', '12798', '12805', '12806', '12820', '12825', '12826',
       '12838', '12839', '12841', '12843', '12858', '12859', '12862',
       '12865', '12866', '12873', '12874', '12877', '12882', '12884',
       '12886', '12889', '12890', '12891', '12892', '12897', '12902',
       '12904', '12935', '12953', '13019', '13021', '13114', '13115',
       '13122', '13123', '13155', '13157', '13217', '13219', '13220',
       '13226', '13227', '13237', '13238', '13240', '13250', '13251',
       '13253', '13255', '13278', '13304', '13305', '13306', '13319',
       '13320', '13347', '13349', '13511', '13512', '13522', '13531',
       '13532', '13583', '13589', '13598', '13611', '13613', '13620',
       '13656', '13669', '13673', '13704', '13707', '13736', '13795',
       '13796', '14015', '14030', '14032', '14038', '14099', '14100',
       '14315', '14316', '14352', '14353', '14354', '14369', '14372',
       '14373', '14519', '14526', '14739', '14745', '14747', '14748',
       '14755', '14779', '14780', '14781', '14782', '14784', '14800',
       '14814', '14815', '14816', '14817', '14818', '14819', '14850',
       '14851', '14853', '14861', '14862', '14863', '14864', '14865',
       '14866', '14867', '14870', '14871', '14872', '14875', '14876',
       '14877', '14878', '14879', '14880', '14881', '14882', '14883',
       '14884', '14993', '15002', '15016', '15182', '15183', '15205',
       '15207', '15208', '15298', '15301', '15303', '15304', '15334',
       '15336', '15340', '15344', '15347', '15350', '15373', '15377',
       '15381', '15387', '15453', '15457', '15514', '15515', '15527',
       '15554', '15560', '15561', '15562', '15566', '15569', '15572',
       '15573', '15590', '15612', '15617', '15629', '15630', '15662',
       '15669', '15670', '15678', '15759', '15760', '15761', '15762',
       '15765', '15767', '15768', '15769', '15770', '15811', '15813',
       '15821', '15822', '15823', '15825', '15827', '15841', '15846',
       '15847', '15877', '15893', '15898', '15904', '15913', '15914',
       '15915', '15916', '15917', '15920', '15925', '15926', '15939',
       '15994', '15995', '15996', '16002', '16039', '16040', '16244',
       '16246', '19729', '19753', '19756', '19790', '19791', '19849',
       '19854', '19874', '19876', '19877', '19878', '19890', '8458',
       '8656', '8901', '8902', '8931', '8961', '8962', '8963', '8978',
       '8979', '8980', '8985', '9284', '9285', '9289', '9290', '9295',
       '9296', '9302', '9391', '9406', '9407', '9408', '9410', '9414',
       '9419', '9431', '9432', '9433', '9455', '9464', '9509', '9510',
       '9512', '9515', '9517', '9518', '9520', '9532', '9540', '9544',
       '9545', '9547', '9553', '9554', '9556', '9557', '9558', '9559',
       '9561', '9563', '9567', '9568', '9569', '9570', '9579', '9580',
       '9584', '9585', '9589', '9592', '9598', '9601', '9602', '9603',
       '9604', '9620', '9623', '9624', '9628', '9629', '9632', '9650',
       '9651', '9652', '9653', '9661', '9675', '9682', '9683', '9688',
       '9690', '9730', '9746', '9751', '9765', '9770', '9796', '9797',
       '9832', '9835', '9837', '9838', '9839', '9844', '9845', '9846',
       '9847', '9848', '9855', '9869', '9974', '9975', '9976', '9977',
       '9978', '9979', '9980', '9981', '9982', '9983', '9985', '9987',
       '9988', '9989', '9992', '9993', 'TP962-A5-P1', 'TP962-A5-P2',
       'TP962-A6-P5', 'TP962-A6-P6', 'TP962-B1-P1', 'TP962-B1-P2',
       'TP962-C12-P1', 'TP962-C12-P2', 'TP962-C6-P1', 'TP962-C6-P2',
       'TP962-E3-P20', 'TP962-E3-P21', 'TP962-E7-P1', 'TP962-E7-P2',
       'TP962-G1-P1', 'TP962-G1-P2', 'TP962-G5-P1', 'TP962-G5-P2',
       'TP962-H10-P1', 'TP962-H10-P2', 'TP962-H7-P1', 'TP962-H7-P2',
       'TP963-A11-P1', 'TP963-A11-P2', 'TP963-A7-P1', 'TP963-A7-P2',
       'TP963-B6-P1', 'TP963-B6-P2', 'TP963-C10-P1', 'TP963-C10-P2',
       'TP963-C11-P1', 'TP963-C11-P2', 'TP963-C2-P1', 'TP963-C2-P2',
       'TP963-C4-P1', 'TP963-C4-P2', 'TP963-C6-P1', 'TP963-C6-P2',
       'TP963-D11-P1', 'TP963-D11-P2', 'TP963-D4-P1', 'TP963-D4-P2',
       'TP963-D8-P1', 'TP963-D8-P2', 'TP963-E9-P1', 'TP963-E9-P2',
       'TP963-F1-P1', 'TP963-F1-P2', 'TP963-G3-P1', 'TP963-G3-P2',
       'TP965-A10-P20', 'TP965-A10-P21', 'TP965-B4-P1', 'TP965-B4-P2',
       'TP965-B6-P1', 'TP965-B6-P2', 'TP965-B7-P1', 'TP965-B7-P2',
       'TP965-B8-P1', 'TP965-B8-P2', 'TP965-C9-P1', 'TP965-C9-P2',
       'TP965-D2-P1', 'TP965-D2-P2', 'TP965-D7-P1', 'TP965-D7-P2',
       'TP965-E12-P1', 'TP965-E12-P2', 'TP965-F10-P1', 'TP965-F10-P2',
       'TP965-F12-P1', 'TP965-F12-P2', 'TP965-H1-P1', 'TP965-H1-P2',
       'TP966-B4-P1', 'TP966-B4-P2', 'TP966-B5-P1', 'TP966-B5-P2',
       'TP966-C1-P1', 'TP966-C1-P2', 'TP966-C7-P1', 'TP966-C7-P2',
       'TP966-C8-P1', 'TP966-C8-P2', 'TP966-E3-P1', 'TP966-E3-P2',
       'TP966-E9-P1', 'TP966-E9-P2', 'TP966-F2-P1', 'TP966-F2-P2',
       'TP966-F8-P1', 'TP966-F8-P2', 'TP966-G3-P1', 'TP966-G3-P2',
       'TP966-G4-P3', 'TP966-G4-P4', 'TP966-G8-P1', 'TP966-G8-P2',
       'TP966-G9-P1', 'TP966-G9-P2', 'TP966-H10-P1', 'TP966-H10-P2',
       'TP966-H2-P1', 'TP966-H2-P2', 'TP967-A10-P1', 'TP967-A10-P2',
       'TP967-A2-P1', 'TP967-A2-P2', 'TP967-B3-P1', 'TP967-B3-P2',
       'TP967-D11-P1', 'TP967-D11-P2', 'TP967-E1-P1', 'TP967-E1-P2',
       'TP967-E9-P1', 'TP967-E9-P2', 'TP967-F1-P1', 'TP967-F1-P2',
       'TP967-F8-P1', 'TP967-F8-P2', 'TP967-G2-P1', 'TP967-G2-P2',
       'TP967-G3-P1', 'TP967-G3-P2', 'TP967-G8-P1', 'TP967-G8-P2',
       'TP967-H2-P1', 'TP967-H2-P2', 'TP967-H3-P1', 'TP967-H3-P2',
       'TP968-A10-P1', 'TP968-A10-P2', 'TP968-A7-P1', 'TP968-A7-P2',
       'TP968-B11-P20', 'TP968-B11-P21', 'TP968-B8-P1', 'TP968-B8-P2',
       'TP968-D6-P1', 'TP968-D6-P2', 'TP968-D9-P1', 'TP968-D9-P2',
       'TP968-E11-P1', 'TP968-E11-P2', 'TP968-F10-P1', 'TP968-F10-P2',
       'TP968-F3-P1', 'TP968-F3-P2', 'TP968-F8-P1', 'TP968-F8-P2',
       'TP968-G6-P1', 'TP968-G6-P2', 'TP968-H10-P1', 'TP968-H10-P2',
       'TP968-H6-P1', 'TP968-H6-P2', 'TP969-A2-P1', 'TP969-A2-P2',
       'TP969-A6-P3', 'TP969-A6-P4', 'TP969-B1-P1', 'TP969-B1-P2',
       'TP969-B3-P1', 'TP969-B3-P2', 'TP969-B6-P3', 'TP969-B6-P4',
       'TP969-C3-P1', 'TP969-C3-P2', 'TP969-D6-P5', 'TP969-D6-P6',
       'TP969-E12-P1', 'TP969-E12-P2', 'TP969-E3-P1', 'TP969-E3-P2',
       'TP969-F10-P1', 'TP969-F10-P2', 'TP969-F4-P1', 'TP969-F4-P2',
       'TP969-G11-P1', 'TP969-G11-P2', 'TP969-G8-P1', 'TP969-G8-P2',
       'TP969-H5-P1', 'TP969-H5-P2', 'TP970-A1-P1', 'TP970-A1-P2',
       'TP970-A7-P1', 'TP970-A7-P2', 'TP970-B11-P1', 'TP970-B11-P2',
       'TP970-B4-P1', 'TP970-B4-P2', 'TP970-B5-P1', 'TP970-B5-P2',
       'TP970-E2-P1', 'TP970-E2-P2', 'TP970-F2-P1', 'TP970-F2-P2',
       'TP970-G4-P1', 'TP970-G4-P2', 'TP970-G6-P1', 'TP970-G6-P2',
       'TP970-H5-P1', 'TP970-H5-P2', 'TP971-A5-P1', 'TP971-A5-P2',
       'TP971-C4-P1', 'TP971-C4-P2', 'TP971-C7-P1', 'TP971-C7-P2',
       'TP971-C9-P1', 'TP971-C9-P2', 'TP971-E1-P1', 'TP971-E1-P2',
       'TP971-E2-P1', 'TP971-E2-P2', 'TP971-E7-P1', 'TP971-E7-P2',
       'TP971-E8-P1', 'TP971-E8-P2', 'TP971-F12-P1', 'TP971-F12-P2',
       'TP971-G12-P1', 'TP971-G12-P2', 'TP971-G5-P1', 'TP971-G5-P2',
       'TP971-G6-P1', 'TP971-G6-P2', 'TP971-G8-P1', 'TP971-G8-P2',
       'TP971-H5-P1', 'TP971-H5-P2', 'TP972-A2-P1', 'TP972-A2-P2',
       'TP972-A9-P1', 'TP972-A9-P2', 'TP972-B6-P1', 'TP972-B6-P2',
       'TP972-C1-P1', 'TP972-C1-P2', 'TP972-C6-P1', 'TP972-C6-P2',
       'TP972-D11-P1', 'TP972-D11-P2', 'TP972-E4-P1', 'TP972-E4-P2',
       'TP972-F1-P3', 'TP972-F1-P4', 'TP972-F3-P1', 'TP972-F3-P2',
       'TP972-F6-P1', 'TP972-F6-P2', 'TP972-G9-P1', 'TP972-G9-P2',
       'TP972-H10-P1', 'TP972-H10-P2', 'TP972-H4-P1', 'TP972-H4-P2',
       'TP972-H6-P1', 'TP972-H6-P2', 'TP973-A2-P1', 'TP973-A2-P2',
       'TP973-B1-P1', 'TP973-B1-P2', 'TP973-C3-P1', 'TP973-C3-P2',
       'TP973-H2-P1', 'TP973-H2-P2', 'TP986-A4-P1', 'TP986-A4-P2',
       'TP986-A5-P1', 'TP986-A5-P2', 'TP986-B2-P1', 'TP986-B2-P2',
       'TP986-C11-P1', 'TP986-C11-P2', 'TP986-C12-P1', 'TP986-C12-P2',
       'TP986-C7-P1', 'TP986-C7-P2', 'TP986-D11-P1', 'TP986-D11-P2',
       'TP986-E10-P1', 'TP986-E10-P2', 'TP986-F1-P3', 'TP986-F1-P4',
       'TP986-G3-P1', 'TP986-G3-P2', 'TP986-G5-P1', 'TP986-G5-P2',
       'TP986-H2-P1', 'TP986-H2-P2', 'TP986-H5-P1', 'TP986-H5-P2'],
      dtype=object)

In [15]:
complete_input_file_path= '/Users/kimd999/research/projects/toxicity/per_each_data/phase_III/input/morpho/full/wide/Tanguay_Phase_3_zf_morphology_data_PNNL_2021MAR23_full_w_14_endpoints_wide_DNC_0_full.csv'
df = pd.read_csv(complete_input_file_path, header = 0)
#print(df.columns)

display(df.head())

display (len(np.unique(df['chemical.id'])))
display (np.unique(df['chemical.id']))

display (len(np.unique(df['plate.id'])))
display (np.unique(df['plate.id']))

,chemical.id,plate.id,well,chemical_plate_well,conc,AXIS,BRN_,CRAN,DNC_,DP24,EDEM,LTRK,MO24,MORT,MUSC,NC__,SKIN,SM24,TCHR
0,725,21511,A01,725_21511_A01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,725,21511,A02,725_21511_A02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,725,21511,A03,725_21511_A03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,725,21511,A04,725_21511_A04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,725,21511,A05,725_21511_A05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

139

array([ 725,  726, 1016, 2585, 2587, 2589, 2590, 2594, 2595, 2596, 2597,
       2598, 2599, 2600, 2685, 2686, 3766, 3771, 3853, 4336, 4337, 4338,
       4339, 4340, 4341, 4342, 4343, 4344, 4345, 4346, 4347, 4348, 4349,
       4350, 4351, 4352, 4353, 4354, 4355, 4356, 4357, 4358, 4359, 4360,
       4361, 4362, 4363, 4364, 4365, 4366, 4367, 4368, 4369, 4370, 4371,
       4372, 4373, 4374, 4375, 4376, 4377, 4378, 4379, 4380, 4381, 4382,
       4383, 4384, 4385, 4386, 4387, 4388, 4390, 4391, 4392, 4393, 4394,
       4395, 4396, 4397, 4398, 4399, 4400, 4401, 4402, 4403, 4404, 4405,
       4406, 4407, 4408, 4410, 4411, 4412, 4413, 4414, 4415, 4416, 4417,
       4418, 4419, 4420, 4421, 4422, 4423, 4424, 4425, 4426, 4427, 4428,
       4429, 4430, 4431, 4432, 4433, 4434, 4435, 4436, 4437, 4438, 4439,
       4440, 4441, 4442, 4443, 4444, 4445, 4446, 4447, 4448, 4449, 4450,
       4451, 4452, 4453, 4454, 4455, 4456, 4457])

278

array([21455, 21456, 21457, 21458, 21459, 21460, 21461, 21462, 21463,
       21464, 21467, 21468, 21469, 21470, 21471, 21472, 21473, 21474,
       21475, 21476, 21478, 21479, 21480, 21481, 21482, 21483, 21484,
       21485, 21486, 21488, 21489, 21490, 21492, 21493, 21494, 21495,
       21496, 21497, 21498, 21499, 21500, 21501, 21502, 21503, 21504,
       21505, 21506, 21507, 21508, 21509, 21511, 21512, 21514, 21515,
       21516, 21517, 21518, 21519, 21520, 21521, 21522, 21523, 21524,
       21525, 21526, 21527, 21528, 21529, 21530, 21531, 21532, 21533,
       21534, 21535, 21536, 21537, 21538, 21539, 21540, 21541, 21542,
       21543, 21544, 21545, 21546, 21547, 21548, 21549, 21550, 21551,
       21552, 21553, 21554, 21556, 21557, 21558, 21559, 21560, 21561,
       21562, 21563, 21564, 21565, 21566, 21567, 21568, 21569, 21570,
       21572, 21573, 21574, 21575, 21576, 21577, 21578, 21579, 21585,
       21586, 21587, 21588, 21589, 21590, 21592, 21593, 21603, 21605,
       21606, 21607, 21608, 21609, 21611, 21612, 21613, 21614, 21615,
       21616, 21617, 21618, 21619, 21620, 21628, 21640, 21641, 21642,
       21643, 21650, 21651, 21652, 21653, 21660, 21661, 21662, 21663,
       21664, 21665, 21666, 21667, 21668, 21669, 21670, 21671, 21672,
       21673, 21674, 21675, 21719, 21803, 21804, 21811, 21830, 21831,
       21832, 21833, 21834, 21841, 21842, 21843, 21844, 21855, 21856,
       21862, 21863, 21871, 21872, 21873, 21874, 21875, 21881, 21882,
       21883, 21884, 21885, 21886, 21887, 21888, 21891, 21892, 21893,
       21894, 21895, 21896, 21897, 21898, 21899, 21900, 21901, 21902,
       21903, 21904, 21905, 21906, 21907, 21908, 21909, 21910, 21923,
       21924, 21925, 21951, 21967, 21971, 21972, 21973, 21974, 21975,
       21976, 21977, 21978, 21979, 21980, 21981, 21982, 21983, 21984,
       21985, 21986, 21987, 21989, 21990, 21991, 21992, 21993, 22006,
       22008, 22030, 22031, 22032, 22033, 22034, 22037, 22040, 22041,
       22042, 22044, 22052, 22053, 22054, 22055, 22092, 22093, 22094,
       22095, 22096, 22097, 22190, 22200, 22201, 22216, 22217, 22219,
       22484, 22485, 22486, 22487, 22488, 22489, 22704, 22712])

In [ ]:
complete_input_file_path= '/Users/kimd999/research/projects/toxicity/per_each_data/phase_III/input/morpho/full/wide/Tanguay_Phase_3_zf_morphology_data_PNNL_2021MAR23_full_w_14_endpoints_wide_DNC_0_full.csv'
df = pd.read_csv(complete_input_file_path, header = 0)

display(df.head())

display (len(np.unique(df['chemical.id'])))
#display (np.unique(df['chemical.id']))

#display (len(np.unique(df['plate.id'])))
#display (np.unique(df['plate.id']))

In [ ]:
# count nan_0_1_data
nan_count = 0
zero_count = 0
one_count = 0
total_count = 0
for (columnName, columnData) in reformatted.iteritems(): 
    if (columnName == "chemical.id") or (columnName == "plate.id") or (columnName == "well") or (columnName == "chemical_plate_well") or (columnName == "conc"):
        continue
#    print('Colunm Name : ', columnName) 
#    print('Column Contents : ', columnData.values[i])
#    print (len(columnData.values))
    for i in range(len(columnData.values)):
        total_count += 1
        if (str(columnData.values[i]) == "nan"):
            nan_count += 1
        elif (str(columnData.values[i]) == "0.0"):
            zero_count += 1
        elif (str(columnData.values[i]) == "1.0"):
            one_count += 1
#        print('Column Contents : ', columnData.values[i])
print ("nan_count:" + str(nan_count))
print ("zero_count:" + str(zero_count))
print ("one_count:" + str(one_count))
print ("total_count:" + str(total_count))

In [ ]:
# divide per chemical.id
    
chemical_id_from_here = np.unique(df['chemical.id'])

full_devel = "full"
#full_devel = "devel"

if (full_devel == "devel"):
    randomly_chosen = random.sample(set(chemical_id_from_here), 2)
    chemical_id_from_here = []
    for i in range(len(randomly_chosen)):
        chemical_id_from_here.append(randomly_chosen[i])

chemical_id_from_here = [53]

for chemical_id in chemical_id_from_here:
    print ("\n", chemical_id)
    df_per_chemical = df.loc[df['chemical.id'] == chemical_id]
    #display(df_per_chemical.head())

    output_filename = "df_per_chemical_" + str(chemical_id) + ".csv"
    df_per_chemical.to_csv(output_filename,index=False)
'''
for chemical_index in chemical_id_from_here:
    print("\nchemical_index:" + str(chemical_index))
    df_per_chemical = df.loc[df['chemical.id'] == chemical_index]
    display(df_per_chemical.head())

    now = datetime.now()

    current_time = now.strftime("%H:%M:%S")
    print("Current Time =", current_time)
'''    
display(df_per_chemical.head())
print ("extraction per chemical is done.")

In [ ]:
complete_input_file_path= '/Users/kimd999/research/projects/toxicity/per_each_data/phase_I_II/input/LPR/latest/after_merging/wide/04_28_2021/344_zf_LPR_data_phase_1_2_2020JUNE25_updated_plate_id_for_TX_tall_fixed_full_240_timepoints_wide_full.csv'
df = pd.read_csv(complete_input_file_path, header = 0)
df = df.rename({'endpoint': 'timepoint'}, axis=1)

display(df.head())

display (len(np.unique(df['chemical.id'])))
display (np.unique(df['chemical.id']))

#display (len(np.unique(df['plate.id'])))
#display (np.unique(df['plate.id']))

In [ ]:
is_NaN = df.isnull()
row_has_NaN = is_NaN.any(axis=1)
rows_with_NaN = df[row_has_NaN]

display(rows_with_NaN.head())
display(rows_with_NaN.tail())
display(len(rows_with_NaN))

In [ ]:
display("before dropna, len(df):"+str(len(df)))
df = df.dropna(how='any')
display("after dropna,  len(df):"+str(len(df)))

In [ ]:
df['chemical.id'] = df['chemical.id'].astype(int)
    
display (len(np.unique(df['chemical.id'])))
display (np.unique(df['chemical.id']))

df['plate.id'] = df['plate.id'].astype(str)
try:
    df['plate.id'] = df['plate.id'].astype(float)
    df['plate.id'] = df['plate.id'].astype(int)
except:
    pass

display (len(np.unique(df['plate.id'])))
display (np.unique(df['plate.id']))

display (df.head())

In [ ]:
len_timepoint = []

chemical_id_from_here = np.unique(df['chemical.id'])
        
total_number_of_chemicals_to_processed = len(chemical_id_from_here)
number_of_chemicals_processed = 0

for chemical_index in chemical_id_from_here:
    df_chemical = df.loc[df['chemical.id'] == chemical_index,:]
    #print("chemical_index:" + str(chemical_index))
    
    len_timepoint.append(len(np.unique(df_chemical['timepoint'])))
    
    #number_of_chemicals_processed += 1
    #write_this = str(number_of_chemicals_processed) + " chemicals processed out of " + str(total_number_of_chemicals_to_processed)
    #print(write_this)

In [ ]:
ds = pd.Series({"Column": len_timepoint})
plt.figure(figsize=(8,4))
#plt.savefig("distribute.png")
sns.countplot(x="Column", data=ds)

In [ ]:
file_path = '/Users/kimd999/research/projects/toxicity/per_each_data/phase_I_II/input/LPR/latest/before_merging/344_zf_LPR_data_phase_1_2_2020JUNE25_updated_plate_id_for_TX_tall_fixed.csv'
df = pd.read_csv(file_path, header = 0)
df = df.rename({'endpoint': 'timepoint'}, axis=1)

display(df.head())

display (len(np.unique(df['chemical.id'])))
display (np.unique(df['chemical.id']))

display (len(np.unique(df['plate.id'])))
display (np.unique(df['plate.id']))

In [ ]:


file_path = '/Users/kimd999/research/projects/toxicity/per_each_data/phase_I_II/input/LPR/after_Lisa_fix/full/tall/344_zf_LPR_data_phase_1_2_2020JUNE25_updated_plate_id_for_TX_tall_fixed.csv'
df = pd.read_csv(file_path, header = 0)
display(df.head())
display(len(df))

display (len(np.unique(df['chemical.id'])))
#display (np.unique(df['chemical.id']))